spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/h2db/libraryms;mode=mysql
    username: sa
    password:

  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true

  # swagger config
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    time-zone: GMT+8

  session:
    store-type: redis

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0