spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2db/test
    username: sa
    password:

  h2:
    console:
      path: /h2
      enabled: true

  # ?? swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
